language: objective-c
osx_image: xcode8.3

branches:
  only:
  - master

env:
  global:
  - NODE_VERSION=stable

install:
- brew tap wix/brew
- brew install applesimutils
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
- export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION

- npm -g install react-native-cli
- npm -g install detox-cli

cache:
  directories:
    - $(npm config get prefix)/bin/detox-cli
script:
- detox build --configuration ios.sim.release
- detox test --configuration ios.sim.release --cleanup
